# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://smithard-rowe.wedding/
title: Eleanor & Chris are getting married!
email: info@smithard-rowe.wedding
author: Eleanor Smithard & Chris Rowe
description: > # "Homepage for the wedding of Eleanor Smithard & Chris Rowe in Doncaster, South Yorkshire on 12 May 2018.
copyright: 'Copyright &copy; 2017-18 Eleanor & Chris. All Rights Reserved.'
credits: 'Credits: forked from Chelsey Contillo and Michael Gully-Santiago.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: envelope-open-o
    text: RSVP
    url: https://smithard-rowe.wedding/rsvp
  - title: spotify
    text: Playlist
    url: https://open.spotify.com/user/cjrowe/playlist/6A1DlrPvkXCHPt8F66RqTV
  - title: gift
    text: Honeymoon List
    url: https://prezola.com/wishlists/10180401
